# Generated by Django 4.0.3 on 2022-04-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoclasses',
            name='doesPass',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='djangoclasses',
            name='isBehind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='djangoclasses',
            name='studentName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='courseNumber',
            field=models.IntegerField(default=''),
        ),
    ]
